version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: start_server.sh > /dev/null 2> /dev/null < /dev/null &
      timeout: 30
      runas: root
