version: 0.2

phases:
  pre_build:
    commands:
      - sudo su
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn package
      - echo  start docker...
      - su docker build -t javademo .
      - su docker tag javademo:latest 687804506828.dkr.ecr.us-east-1.amazonaws.com/javademo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - su docker push 687804506828.dkr.ecr.us-east-1.amazonaws.com/javademo:latest
artifacts:
  files:
    - target/demoforcicd-1.0-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
