version: 0.2


phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - mvn package
      - echo Build completed on `date`
artifacts:
  files:
    - target/demoforcicd-1.0-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
